### ISSUE TITLE
`invoke()` are suspend functions

### ISSUE THREAD

**Issue by sschuberth** [MayakaApps/Kache#108]
All the Kache-class constructors are private, to they can only be instantiated via the `invoke()` operators. These function, however, are suspend function. That makes migration from DiskLru not very straight-forward, as you cannot easily swap out a top-level class property which used to be a DiskLru to e.g. a FileKache.

What's the recommendation here? Also, I'm curious about the design choice to disallow creating a FileKache / OkioFileKache directory, which would have avoided this pitfall.

**Comment by MSDarwish2000** [comment]
I understand that it is not convenient, but it is not a degradation as `DiskLruCache` also had a private constructor and the only way to initialize it was through suspend `open()` function. suspend function is needed as the function does IO operations that shouldn't be blocking anyway. So, the two options that are available are:

- The current implementation and if I had to use a top-level property, I would use Kotlin's `lateinit var`
- Splitting class construction and the actual cache and journal processing logic, but still the cache wouldn't be useful before calling a suspending open function, so the user still needs to check for something like `isOpen` instead of checking for `isInitialized` in the current suggested way

**Comment by sschuberth** [comment]
I decided to simply wrap the `invoke()` call in `runBlocking` instead for now, thanks.
